name: 'SSSH Simple Remote Run'
description: 'Executing remote ssh commands'
branding:
  icon: 'terminal'
  color: 'gray-dark'

inputs:
  host:
    description: 'ssh host'
  username:
    description: 'ssh username'
  key_path:
    description: 'path of ssh private key'
  script:
    description: 'execute commands'

runs:
  using: 'composite'
  steps:
    - run: ssh -o StrictHostKeyChecking=no -i ${{ inputs.key_path }} ${{ inputs.username }}@${{ inputs.host }} "${{ inputs.script }}"
      shell: bash
