name: 'SSSH Simple Remote Run'
description: 'Executing remote ssh commands'
inputs:
  host:
    description: 'ssh host'
  port:
    description: 'ssh port'
    default: 22
  username:
    description: 'ssh username'
  key_path:
    description: 'path of ssh private key'
  script:
    description: 'execute commands'
branding:
  icon: 'terminal'
  color: 'gray-dark'
runs:
  using: 'composite'
  steps:
    - run: ssh -p ${{ inputs.port }} -i ${{ inputs.key_path }} ${{ inputs.username }}@${{ inputs.host }} "${{ inputs.script }}"
      shell: bash
